apiVersion: apps/v1
kind: Deployment
metadata:
  name: GoViolin-deployment
  labels:
    app: goviolin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goviolin
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      containers:
      - name: goviolin
        image: walednegm/gov:1.0
        ports:
        - containerPort: 8080
